[project]
name = "cs-fundamentals"
version = "0.1.0"
description = "Python project to hone computer science fundamentals of data structures, algorithms and problem solving patterns"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "httpx>=0.28.1",
    "pydantic-settings>=2.11.0",
    "numpy>=2.2.5",
    "pytest>=8.3.5",
    "pytest-asyncio>=1.2.0",
    "uvicorn>=0.23.2",
]

#
# Build config
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["cs_fundamentals*"]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "ruff>=0.11.7",
]

#
# Test config
[tool.pytest.ini_options]
testpaths = ["automation"]
pythonpath = ["."]
addopts = "-q -p no:warnings"
filterwarnings = [
  "ignore::pytest.PytestAssertRewriteWarning",
  "ignore:The configuration option \"asyncio_default_fixture_loop_scope\" is unset.:pytest.PytestDeprecationWarning",
]
# Set an explicit default to silence the deprecation in pytest-asyncio:
asyncio_default_fixture_loop_scope = "function"

#
# Linter/Formatter configs
[tool.ruff]
show-fixes = true
target-version = "py310"
line-length = 100

[tool.ruff.lint]
extend-select = [
    "C4",      # Flake8 Comprehensions
    "SIM",     # Flake8 Simulations
    "TC",      # Flake8 Type Checker
    "UP",      # PyUpgrade
    "ANN201",  # Missing return type annotation for public function {name}
    "ANN202",  # Missing return type annotation for private function {name}
    "ANN204",  # Missing return type annotation for special method {name}
    "ANN205",  # Missing return type annotation for staticmethod {name}
    "ANN206",  # Missing return type annotation for classmethod {name}
    "TID252",  # Disallow relative imports; prefer absolute
]
ignore = [
    "E501",    # Line too long ({width} > {limit})
    "F403"     # 'from module import *' used; unable to detect undefined names
]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
