apiVersion: v2
name: cs-fundamentals
description: A Helm chart for deploying the cs-fundamentals FastAPI service
type: application
version: 0.7.2  # x-release-please-version
appVersion: "0.7.2"  # x-release-please-version
