image:
  # repository: ghcr.io/jasoncorrea56/cs-fundamentals
  repository: 948319129176.dkr.ecr.us-west-2.amazonaws.com/cs-fundamentals
  tag: "v0.1.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  annotations: {}

probes:
  path: /api/v1/healthz
  timeoutSeconds: 2
  periodSeconds: 10
  failureThreshold: 3
  successThreshold: 1
  initialDelaySeconds: 5

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /api/v1/healthz
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-west-2:948319129176:certificate/e6b92505-243a-45a0-bb66-54474bf1fac3"
  hosts:
    - host: "csf.jasoncorrea.com"   # ExternalDNS uses to create the A record
      paths:
        - path: /
          pathType: Prefix
  # Optional TLS block for ALB TLS termination (ALB uses annotation above).
  # Empty is fine, but including host for clarity.
  tls: {}
    # - hosts: ["csf.jasoncorrea.com"]

serviceAccount:
  create: false
  name: "csf-app"
  annotations: {}

podAnnotations: {}
podLabels: {}

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  # targetMemoryUtilizationPercentage: 80

pdb:
  enabled: false
  minAvailable: 1

nodeSelector: {}
tolerations: []
affinity: {}

env:
  - name: LOG_LEVEL
    value: "info"
  - name: DB_URL
    valueFrom:
      secretKeyRef:
        name: csf-db
        key: DB_URL

config:
  enabled: true
  mountPath: /app/config
  data:
    APP_NAME: cs-fundamentals
    FEATURE_FLAG_EXAMPLE: "false"

# Base64-encoded values can be provided via extraManifests or directly with stringData
secret:
  enabled: false
  stringData: {}
