replicaCount: 1

image:
  # Use the locally built image name (no registry)
  repository: cs-fundamentals
  tag: dev
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  name: csf-app

# Disable AWS Secrets Store CSI for minikube
secretsStore:
  enabled: false

# Create a simple K8s Secret in minikube for DB_URL
secret:
  enabled: true
  name: csf-db
  data: {}
  external: false

env:
  - name: LOG_LEVEL
    value: info
  - name: DB_URL
    valueFrom:
      secretKeyRef:
        name: csf-db
        key: DB_URL

service:
  type: NodePort
  port: 80
  targetPort: 8080

# Ingress is usually off for minikube unless running nginx ingress locally
ingress:
  enabled: false
